In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
filepath = "/content/drive/MyDrive/DeepLearning/data.txt"

Read data from file , Split into sentences and assign numbers to each unique word using tokenizer

In [ ]:
data = ""
with open(filepath , 'r' , encoding = "utf-8") as f:
    data = f.read()

my_list = data.split('.')
my_list = [sen for sen in my_list if len(sen) > 2]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(my_list)
tokenizer.word_index


{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'i': 6,
 '”': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'he': 11,
 'was': 12,
 'you': 13,
 'his': 14,
 'is': 15,
 'my': 16,
 'have': 17,
 'with': 18,
 'as': 19,
 'had': 20,
 'at': 21,
 'which': 22,
 'for': 23,
 'be': 24,
 'not': 25,
 'me': 26,
 'but': 27,
 'from': 28,
 'we': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'there': 33,
 'holmes': 34,
 'him': 35,
 'so': 36,
 'her': 37,
 'she': 38,
 'all': 39,
 '’': 40,
 'been': 41,
 'your': 42,
 'on': 43,
 'very': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 '“i': 48,
 'were': 49,
 'an': 50,
 'no': 51,
 'would': 52,
 'out': 53,
 'what': 54,
 'then': 55,
 'up': 56,
 'when': 57,
 'man': 58,
 'could': 59,
 'has': 60,
 'do': 61,
 'into': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'who': 66,
 'mr': 67,
 'if': 68,
 'some': 69,
 'down': 70,
 'see': 71,
 'now': 72,
 'our': 73,
 'should': 74,
 'may': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'they': 79,
 'can': 80,
 'more': 81,
 'think': 82,
 'about': 83,
 'mu

convert english sentences into numbers and save in a list and make features by adding one more word

In [ ]:
input_seq=[]
print(len(my_list))
for i in my_list:
    tokenized_sentence=tokenizer.texts_to_sequences([i])[0]
    # print(tokenized_sentence[0])

    for i in range(1,len(tokenized_sentence)):
        input_seq.append(tokenized_sentence[:i+1])


6344


In [ ]:
# print(len(input_seq))
# print(input_seq)
input_seq

[[4787, 145],
 [4787, 145, 4788],
 [4787, 145, 4788, 1],
 [4787, 145, 4788, 1, 1015],
 [4787, 145, 4788, 1, 1015, 4],
 [4787, 145, 4788, 1, 1015, 4, 128],
 [4787, 145, 4788, 1, 1015, 4, 128, 34],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609, 2231],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609, 2231, 2232],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609, 2231, 2232, 30],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609, 2231, 2232, 30, 1016],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609, 2231, 2232, 30, 1016, 15],
 [4787, 145, 4788, 1, 1015, 4, 128, 34, 45, 609, 2231, 2232, 30, 1016, 15, 23],
 [4787,
  145,
  4788,
  1,
  1015,
  4,
  128,
  34,
  45,
  609,
  2231,
  2232,
  30,
  1016,
  15,
  23,
  1],
 [4787,
  145,
  4788,
  1,
  1015,
  4,
  128,
  34,
  45,
  609,
  2231,
  2232,
  30,
  1016,
  15,
  23,
  1,
  274],
 [4787,
  145,
  4788,
  1,
  1015,
  4,
  128,
  34,
  45,


In [ ]:
max_len = max([len(x) for x in input_seq])
max_len

105

Add padded zeros to make size of features same for seupervised learning

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input = pad_sequences(input_seq , maxlen = max_len , padding = 'pre')
padded_input

array([[   0,    0,    0, ...,    0, 4787,  145],
       [   0,    0,    0, ..., 4787,  145, 4788],
       [   0,    0,    0, ...,  145, 4788,    1],
       ...,
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358],
       [   0,    0,    0, ...,   83,  358, 1666]], dtype=int32)

  Separate input and output from padded vector

In [ ]:
X = padded_input[:,:-1]

In [ ]:
Y = padded_input[:,-1]

In [ ]:
Y

array([ 145, 4788,    1, ...,   83,  358, 1666], dtype=int32)

In [ ]:
print(X.shape)
print(Y.shape)

(104820, 104)
(104820,)


One hot encoding of Y accoroding to no of words unique in my data (tokenizer)

one hot encoding starts from 0 thats why 1 added to length

In [ ]:
from tensorflow.keras.utils import to_categorical
Y = to_categorical(Y , num_classes = len(tokenizer.word_index)+1)

In [ ]:
Y.shape

(104820, 8929)

In [ ]:
import numpy as np
Y = np.argmax(Y, axis=1)

In [ ]:
Y.shape

(104820,)

In [ ]:
Y[:4]

array([ 145, 4788,    1, 1015])

Build architecture of model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , LSTM , Dense


Embedding layer ka main faida ye hai ke wo words ko numbers se vectors me convert karta hai — aur wo vectors meaningful relationships sikhtay hain.

Dense layer os fro output calulation based on activation function as it is multiclass classification

In [ ]:
model = Sequential()
model.add(Embedding(8929 , 100 ))
model.add(LSTM(150)) #no of nodes in every gate
model.add(Dense(8929 , activation = 'softmax')) #no of words in vocab as need prob of each word in prob to give answer

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.build(input_shape=(None, 104))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 104, 100)       │       892,900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 8929)           │     1,348,279 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,391,779 (9.12 MB)

 Trainable params: 2,391,779 (9.12 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
X

array([[   0,    0,    0, ...,    0,    0, 4787],
       [   0,    0,    0, ...,    0, 4787,  145],
       [   0,    0,    0, ..., 4787,  145, 4788],
       ...,
       [   0,    0,    0, ..., 8928,    3,  360],
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358]], dtype=int32)

In [ ]:
model.fit(X , Y , epochs = 100)

Epoch 1/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 36s 9ms/step - accuracy: 0.0645 - loss: 6.6634
Epoch 2/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 38s 9ms/step - accuracy: 0.1306 - loss: 5.5174
Epoch 3/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 40s 9ms/step - accuracy: 0.1554 - loss: 5.0458
Epoch 4/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 31s 9ms/step - accuracy: 0.1758 - loss: 4.6626
Epoch 5/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 41s 9ms/step - accuracy: 0.1986 - loss: 4.3014
Epoch 6/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 41s 9ms/step - accuracy: 0.2245 - loss: 4.0011
Epoch 7/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 30s 9ms/step - accuracy: 0.2584 - loss: 3.7029
Epoch 8/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 41s 9ms/step - accuracy: 0.2946 - loss: 3.4248
Epoch 9/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 41s 9ms/step - accuracy: 0.3347 - loss: 3.1704
Epoch 10/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 30s 9ms/step - accuracy: 0.3718 - loss: 2.9459
Epoch 11/100
3276/3276 ━━━━━━━━━━━━━━━━━━━━ 41s 9ms/step - accuracy: 0.4107 - loss: 2.7414
Epoch 12

In [ ]:
from google.colab import drive
drive.mount('/content/MyDrive')

Mounted at /content/MyDrive


In [ ]:
from tensorflow import keras
model = keras.models.load_model('/content/drive/MyDrive/DeepLearning/Next_Word_Predictor.keras')

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


loading and Model Prediction

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import time

text = "me pagal hu"
for i in range(11):
  # token
  token_text = tokenizer.texts_to_sequences([text])[0]
  # # padding
  padded_text = pad_sequences( [token_text] ,maxlen= 104 , padding = 'pre' )

  predicted_position = np.argmax(model.predict(padded_text), axis=-1)

  for word,index in tokenizer.word_index.items():
      if index == predicted_position:
          text = text + " " + word
          print(text)
          time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
me pagal hu watson
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
me pagal hu watson i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
me pagal hu watson i have
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
me pagal hu watson i have no
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
me pagal hu watson i have no sense
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
me pagal hu watson i have no sense to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
me pagal hu watson i have no sense to stay
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
me pagal hu watson i have no sense to stay ”
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
me pagal hu watson i have no sense to stay ” said
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
me pagal hu watson i have no sense to stay ” said i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
me pagal hu watson i have no sense to stay ” said i “for


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
it
